apiVersion: v1
kind: Service
metadata:
  name: cs-loadbalancer
  namespace: clickstack
  labels:
    app: clickstack
spec:
  type: LoadBalancer
  selector:
    app: clickstack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  sessionAffinity: None
